---
- name: Set up web server
  hosts: Servers
  become: true
  become_user: root
  gather_facts: true

  tasks:
    - name: "Install Apache"
      package: name=apache2 state=present
    - name: "Hello World"
      copy: content="<!DOCTYPE html>
            <html>
              <head>  
                <meta charset="UTF-8">
                <title>Homework 1</title>
              </head>

              <body>
                Hello World!
              </body>
            </html>" dest=/var/www/html/index.html